/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardTablesRouteImport } from './routes/dashboard.tables'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as DashboardConnectionsRouteImport } from './routes/dashboard.connections'
import { Route as DashboardBiRouteImport } from './routes/dashboard.bi'
import { Route as DashboardApisRouteImport } from './routes/dashboard.apis'
import { Route as DashboardAgentRouteImport } from './routes/dashboard.agent'
import { Route as ApiPublicAgentManifestRouteImport } from './routes/api.public.agent.manifest'
import { Route as ApiPublicAgentIngestRouteImport } from './routes/api.public.agent.ingest'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTablesRoute = DashboardTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConnectionsRoute = DashboardConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBiRoute = DashboardBiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApisRoute = DashboardApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentRoute = DashboardAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicAgentManifestRoute = ApiPublicAgentManifestRouteImport.update({
  id: '/api/public/agent/manifest',
  path: '/api/public/agent/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentIngestRoute = ApiPublicAgentIngestRouteImport.update({
  id: '/api/public/agent/ingest',
  path: '/api/public/agent/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/apis': typeof DashboardApisRoute
  '/dashboard/bi': typeof DashboardBiRoute
  '/dashboard/connections': typeof DashboardConnectionsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/api/public/agent/ingest': typeof ApiPublicAgentIngestRoute
  '/api/public/agent/manifest': typeof ApiPublicAgentManifestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/apis': typeof DashboardApisRoute
  '/dashboard/bi': typeof DashboardBiRoute
  '/dashboard/connections': typeof DashboardConnectionsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/api/public/agent/ingest': typeof ApiPublicAgentIngestRoute
  '/api/public/agent/manifest': typeof ApiPublicAgentManifestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/apis': typeof DashboardApisRoute
  '/dashboard/bi': typeof DashboardBiRoute
  '/dashboard/connections': typeof DashboardConnectionsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/api/public/agent/ingest': typeof ApiPublicAgentIngestRoute
  '/api/public/agent/manifest': typeof ApiPublicAgentManifestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/agent'
    | '/dashboard/apis'
    | '/dashboard/bi'
    | '/dashboard/connections'
    | '/dashboard/logs'
    | '/dashboard/settings'
    | '/dashboard/tables'
    | '/api/public/agent/ingest'
    | '/api/public/agent/manifest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/agent'
    | '/dashboard/apis'
    | '/dashboard/bi'
    | '/dashboard/connections'
    | '/dashboard/logs'
    | '/dashboard/settings'
    | '/dashboard/tables'
    | '/api/public/agent/ingest'
    | '/api/public/agent/manifest'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/agent'
    | '/dashboard/apis'
    | '/dashboard/bi'
    | '/dashboard/connections'
    | '/dashboard/logs'
    | '/dashboard/settings'
    | '/dashboard/tables'
    | '/api/public/agent/ingest'
    | '/api/public/agent/manifest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicAgentIngestRoute: typeof ApiPublicAgentIngestRoute
  ApiPublicAgentManifestRoute: typeof ApiPublicAgentManifestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tables': {
      id: '/dashboard/tables'
      path: '/tables'
      fullPath: '/dashboard/tables'
      preLoaderRoute: typeof DashboardTablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/connections': {
      id: '/dashboard/connections'
      path: '/connections'
      fullPath: '/dashboard/connections'
      preLoaderRoute: typeof DashboardConnectionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bi': {
      id: '/dashboard/bi'
      path: '/bi'
      fullPath: '/dashboard/bi'
      preLoaderRoute: typeof DashboardBiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/apis': {
      id: '/dashboard/apis'
      path: '/apis'
      fullPath: '/dashboard/apis'
      preLoaderRoute: typeof DashboardApisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agent': {
      id: '/dashboard/agent'
      path: '/agent'
      fullPath: '/dashboard/agent'
      preLoaderRoute: typeof DashboardAgentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/agent/manifest': {
      id: '/api/public/agent/manifest'
      path: '/api/public/agent/manifest'
      fullPath: '/api/public/agent/manifest'
      preLoaderRoute: typeof ApiPublicAgentManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/ingest': {
      id: '/api/public/agent/ingest'
      path: '/api/public/agent/ingest'
      fullPath: '/api/public/agent/ingest'
      preLoaderRoute: typeof ApiPublicAgentIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAgentRoute: typeof DashboardAgentRoute
  DashboardApisRoute: typeof DashboardApisRoute
  DashboardBiRoute: typeof DashboardBiRoute
  DashboardConnectionsRoute: typeof DashboardConnectionsRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTablesRoute: typeof DashboardTablesRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgentRoute: DashboardAgentRoute,
  DashboardApisRoute: DashboardApisRoute,
  DashboardBiRoute: DashboardBiRoute,
  DashboardConnectionsRoute: DashboardConnectionsRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTablesRoute: DashboardTablesRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicAgentIngestRoute: ApiPublicAgentIngestRoute,
  ApiPublicAgentManifestRoute: ApiPublicAgentManifestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
