/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardTablesRouteImport } from './routes/dashboard.tables'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as DashboardConnectionsRouteImport } from './routes/dashboard.connections'
import { Route as DashboardBiScriptsRouteImport } from './routes/dashboard.bi-scripts'
import { Route as DashboardApisRouteImport } from './routes/dashboard.apis'
import { Route as DashboardAgentRouteImport } from './routes/dashboard.agent'
import { Route as ApiPublicMirrorTablesRouteImport } from './routes/api.public.mirror.tables'
import { Route as ApiPublicMirrorQueryRouteImport } from './routes/api.public.mirror.query'
import { Route as ApiPublicMirrorAllPksRouteImport } from './routes/api.public.mirror.all-pks'
import { Route as ApiPublicMaintenanceCleanupLogsRouteImport } from './routes/api.public.maintenance.cleanup-logs'
import { Route as ApiPublicBiSnapshotRouteImport } from './routes/api.public.bi.snapshot'
import { Route as ApiPublicBiRunScriptsRouteImport } from './routes/api.public.bi.run-scripts'
import { Route as ApiPublicBiPushRouteImport } from './routes/api.public.bi.push'
import { Route as ApiPublicBiForceRefreshRouteImport } from './routes/api.public.bi.force-refresh'
import { Route as ApiPublicAgentManifestRouteImport } from './routes/api.public.agent.manifest'
import { Route as ApiPublicAgentIngestRouteImport } from './routes/api.public.agent.ingest'
import { Route as ApiPublicAgentHeartbeatRouteImport } from './routes/api.public.agent.heartbeat'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTablesRoute = DashboardTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConnectionsRoute = DashboardConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBiScriptsRoute = DashboardBiScriptsRouteImport.update({
  id: '/bi-scripts',
  path: '/bi-scripts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApisRoute = DashboardApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentRoute = DashboardAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicMirrorTablesRoute = ApiPublicMirrorTablesRouteImport.update({
  id: '/api/public/mirror/tables',
  path: '/api/public/mirror/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMirrorQueryRoute = ApiPublicMirrorQueryRouteImport.update({
  id: '/api/public/mirror/query',
  path: '/api/public/mirror/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMirrorAllPksRoute = ApiPublicMirrorAllPksRouteImport.update({
  id: '/api/public/mirror/all-pks',
  path: '/api/public/mirror/all-pks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMaintenanceCleanupLogsRoute =
  ApiPublicMaintenanceCleanupLogsRouteImport.update({
    id: '/api/public/maintenance/cleanup-logs',
    path: '/api/public/maintenance/cleanup-logs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBiSnapshotRoute = ApiPublicBiSnapshotRouteImport.update({
  id: '/api/public/bi/snapshot',
  path: '/api/public/bi/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBiRunScriptsRoute = ApiPublicBiRunScriptsRouteImport.update({
  id: '/api/public/bi/run-scripts',
  path: '/api/public/bi/run-scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBiPushRoute = ApiPublicBiPushRouteImport.update({
  id: '/api/public/bi/push',
  path: '/api/public/bi/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBiForceRefreshRoute = ApiPublicBiForceRefreshRouteImport.update({
  id: '/api/public/bi/force-refresh',
  path: '/api/public/bi/force-refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentManifestRoute = ApiPublicAgentManifestRouteImport.update({
  id: '/api/public/agent/manifest',
  path: '/api/public/agent/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentIngestRoute = ApiPublicAgentIngestRouteImport.update({
  id: '/api/public/agent/ingest',
  path: '/api/public/agent/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentHeartbeatRoute = ApiPublicAgentHeartbeatRouteImport.update({
  id: '/api/public/agent/heartbeat',
  path: '/api/public/agent/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/apis': typeof DashboardApisRoute
  '/dashboard/bi-scripts': typeof DashboardBiScriptsRoute
  '/dashboard/connections': typeof DashboardConnectionsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/ingest': typeof ApiPublicAgentIngestRoute
  '/api/public/agent/manifest': typeof ApiPublicAgentManifestRoute
  '/api/public/bi/force-refresh': typeof ApiPublicBiForceRefreshRoute
  '/api/public/bi/push': typeof ApiPublicBiPushRoute
  '/api/public/bi/run-scripts': typeof ApiPublicBiRunScriptsRoute
  '/api/public/bi/snapshot': typeof ApiPublicBiSnapshotRoute
  '/api/public/maintenance/cleanup-logs': typeof ApiPublicMaintenanceCleanupLogsRoute
  '/api/public/mirror/all-pks': typeof ApiPublicMirrorAllPksRoute
  '/api/public/mirror/query': typeof ApiPublicMirrorQueryRoute
  '/api/public/mirror/tables': typeof ApiPublicMirrorTablesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/apis': typeof DashboardApisRoute
  '/dashboard/bi-scripts': typeof DashboardBiScriptsRoute
  '/dashboard/connections': typeof DashboardConnectionsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/ingest': typeof ApiPublicAgentIngestRoute
  '/api/public/agent/manifest': typeof ApiPublicAgentManifestRoute
  '/api/public/bi/force-refresh': typeof ApiPublicBiForceRefreshRoute
  '/api/public/bi/push': typeof ApiPublicBiPushRoute
  '/api/public/bi/run-scripts': typeof ApiPublicBiRunScriptsRoute
  '/api/public/bi/snapshot': typeof ApiPublicBiSnapshotRoute
  '/api/public/maintenance/cleanup-logs': typeof ApiPublicMaintenanceCleanupLogsRoute
  '/api/public/mirror/all-pks': typeof ApiPublicMirrorAllPksRoute
  '/api/public/mirror/query': typeof ApiPublicMirrorQueryRoute
  '/api/public/mirror/tables': typeof ApiPublicMirrorTablesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/apis': typeof DashboardApisRoute
  '/dashboard/bi-scripts': typeof DashboardBiScriptsRoute
  '/dashboard/connections': typeof DashboardConnectionsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/ingest': typeof ApiPublicAgentIngestRoute
  '/api/public/agent/manifest': typeof ApiPublicAgentManifestRoute
  '/api/public/bi/force-refresh': typeof ApiPublicBiForceRefreshRoute
  '/api/public/bi/push': typeof ApiPublicBiPushRoute
  '/api/public/bi/run-scripts': typeof ApiPublicBiRunScriptsRoute
  '/api/public/bi/snapshot': typeof ApiPublicBiSnapshotRoute
  '/api/public/maintenance/cleanup-logs': typeof ApiPublicMaintenanceCleanupLogsRoute
  '/api/public/mirror/all-pks': typeof ApiPublicMirrorAllPksRoute
  '/api/public/mirror/query': typeof ApiPublicMirrorQueryRoute
  '/api/public/mirror/tables': typeof ApiPublicMirrorTablesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/agent'
    | '/dashboard/apis'
    | '/dashboard/bi-scripts'
    | '/dashboard/connections'
    | '/dashboard/logs'
    | '/dashboard/settings'
    | '/dashboard/tables'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/ingest'
    | '/api/public/agent/manifest'
    | '/api/public/bi/force-refresh'
    | '/api/public/bi/push'
    | '/api/public/bi/run-scripts'
    | '/api/public/bi/snapshot'
    | '/api/public/maintenance/cleanup-logs'
    | '/api/public/mirror/all-pks'
    | '/api/public/mirror/query'
    | '/api/public/mirror/tables'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/agent'
    | '/dashboard/apis'
    | '/dashboard/bi-scripts'
    | '/dashboard/connections'
    | '/dashboard/logs'
    | '/dashboard/settings'
    | '/dashboard/tables'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/ingest'
    | '/api/public/agent/manifest'
    | '/api/public/bi/force-refresh'
    | '/api/public/bi/push'
    | '/api/public/bi/run-scripts'
    | '/api/public/bi/snapshot'
    | '/api/public/maintenance/cleanup-logs'
    | '/api/public/mirror/all-pks'
    | '/api/public/mirror/query'
    | '/api/public/mirror/tables'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/agent'
    | '/dashboard/apis'
    | '/dashboard/bi-scripts'
    | '/dashboard/connections'
    | '/dashboard/logs'
    | '/dashboard/settings'
    | '/dashboard/tables'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/ingest'
    | '/api/public/agent/manifest'
    | '/api/public/bi/force-refresh'
    | '/api/public/bi/push'
    | '/api/public/bi/run-scripts'
    | '/api/public/bi/snapshot'
    | '/api/public/maintenance/cleanup-logs'
    | '/api/public/mirror/all-pks'
    | '/api/public/mirror/query'
    | '/api/public/mirror/tables'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicAgentHeartbeatRoute: typeof ApiPublicAgentHeartbeatRoute
  ApiPublicAgentIngestRoute: typeof ApiPublicAgentIngestRoute
  ApiPublicAgentManifestRoute: typeof ApiPublicAgentManifestRoute
  ApiPublicBiForceRefreshRoute: typeof ApiPublicBiForceRefreshRoute
  ApiPublicBiPushRoute: typeof ApiPublicBiPushRoute
  ApiPublicBiRunScriptsRoute: typeof ApiPublicBiRunScriptsRoute
  ApiPublicBiSnapshotRoute: typeof ApiPublicBiSnapshotRoute
  ApiPublicMaintenanceCleanupLogsRoute: typeof ApiPublicMaintenanceCleanupLogsRoute
  ApiPublicMirrorAllPksRoute: typeof ApiPublicMirrorAllPksRoute
  ApiPublicMirrorQueryRoute: typeof ApiPublicMirrorQueryRoute
  ApiPublicMirrorTablesRoute: typeof ApiPublicMirrorTablesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tables': {
      id: '/dashboard/tables'
      path: '/tables'
      fullPath: '/dashboard/tables'
      preLoaderRoute: typeof DashboardTablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/connections': {
      id: '/dashboard/connections'
      path: '/connections'
      fullPath: '/dashboard/connections'
      preLoaderRoute: typeof DashboardConnectionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bi-scripts': {
      id: '/dashboard/bi-scripts'
      path: '/bi-scripts'
      fullPath: '/dashboard/bi-scripts'
      preLoaderRoute: typeof DashboardBiScriptsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/apis': {
      id: '/dashboard/apis'
      path: '/apis'
      fullPath: '/dashboard/apis'
      preLoaderRoute: typeof DashboardApisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agent': {
      id: '/dashboard/agent'
      path: '/agent'
      fullPath: '/dashboard/agent'
      preLoaderRoute: typeof DashboardAgentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/mirror/tables': {
      id: '/api/public/mirror/tables'
      path: '/api/public/mirror/tables'
      fullPath: '/api/public/mirror/tables'
      preLoaderRoute: typeof ApiPublicMirrorTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mirror/query': {
      id: '/api/public/mirror/query'
      path: '/api/public/mirror/query'
      fullPath: '/api/public/mirror/query'
      preLoaderRoute: typeof ApiPublicMirrorQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mirror/all-pks': {
      id: '/api/public/mirror/all-pks'
      path: '/api/public/mirror/all-pks'
      fullPath: '/api/public/mirror/all-pks'
      preLoaderRoute: typeof ApiPublicMirrorAllPksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/maintenance/cleanup-logs': {
      id: '/api/public/maintenance/cleanup-logs'
      path: '/api/public/maintenance/cleanup-logs'
      fullPath: '/api/public/maintenance/cleanup-logs'
      preLoaderRoute: typeof ApiPublicMaintenanceCleanupLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bi/snapshot': {
      id: '/api/public/bi/snapshot'
      path: '/api/public/bi/snapshot'
      fullPath: '/api/public/bi/snapshot'
      preLoaderRoute: typeof ApiPublicBiSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bi/run-scripts': {
      id: '/api/public/bi/run-scripts'
      path: '/api/public/bi/run-scripts'
      fullPath: '/api/public/bi/run-scripts'
      preLoaderRoute: typeof ApiPublicBiRunScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bi/push': {
      id: '/api/public/bi/push'
      path: '/api/public/bi/push'
      fullPath: '/api/public/bi/push'
      preLoaderRoute: typeof ApiPublicBiPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bi/force-refresh': {
      id: '/api/public/bi/force-refresh'
      path: '/api/public/bi/force-refresh'
      fullPath: '/api/public/bi/force-refresh'
      preLoaderRoute: typeof ApiPublicBiForceRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/manifest': {
      id: '/api/public/agent/manifest'
      path: '/api/public/agent/manifest'
      fullPath: '/api/public/agent/manifest'
      preLoaderRoute: typeof ApiPublicAgentManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/ingest': {
      id: '/api/public/agent/ingest'
      path: '/api/public/agent/ingest'
      fullPath: '/api/public/agent/ingest'
      preLoaderRoute: typeof ApiPublicAgentIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/heartbeat': {
      id: '/api/public/agent/heartbeat'
      path: '/api/public/agent/heartbeat'
      fullPath: '/api/public/agent/heartbeat'
      preLoaderRoute: typeof ApiPublicAgentHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAgentRoute: typeof DashboardAgentRoute
  DashboardApisRoute: typeof DashboardApisRoute
  DashboardBiScriptsRoute: typeof DashboardBiScriptsRoute
  DashboardConnectionsRoute: typeof DashboardConnectionsRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTablesRoute: typeof DashboardTablesRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgentRoute: DashboardAgentRoute,
  DashboardApisRoute: DashboardApisRoute,
  DashboardBiScriptsRoute: DashboardBiScriptsRoute,
  DashboardConnectionsRoute: DashboardConnectionsRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTablesRoute: DashboardTablesRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicAgentHeartbeatRoute: ApiPublicAgentHeartbeatRoute,
  ApiPublicAgentIngestRoute: ApiPublicAgentIngestRoute,
  ApiPublicAgentManifestRoute: ApiPublicAgentManifestRoute,
  ApiPublicBiForceRefreshRoute: ApiPublicBiForceRefreshRoute,
  ApiPublicBiPushRoute: ApiPublicBiPushRoute,
  ApiPublicBiRunScriptsRoute: ApiPublicBiRunScriptsRoute,
  ApiPublicBiSnapshotRoute: ApiPublicBiSnapshotRoute,
  ApiPublicMaintenanceCleanupLogsRoute: ApiPublicMaintenanceCleanupLogsRoute,
  ApiPublicMirrorAllPksRoute: ApiPublicMirrorAllPksRoute,
  ApiPublicMirrorQueryRoute: ApiPublicMirrorQueryRoute,
  ApiPublicMirrorTablesRoute: ApiPublicMirrorTablesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
